/*
 * Copyright 2023 RAW Labs S.A.
 *
 * Use of this software is governed by the Business Source License
 * included in the file licenses/BSL.txt.
 *
 * As of the Change Date specified in that file, in accordance with
 * the Business Source License, use of this software will be governed
 * by the Apache License, Version 2.0, included in the file
 * licenses/APL.txt.
 */

package raw.compiler.rql2.truffle.builtin

import raw.compiler.rql2.truffle.TruffleWithLocalCredentialsTestContext
import raw.testing.tags.TruffleTests
import raw.compiler.rql2.tests.builtin._

@TruffleTests class BinaryPackageTruffleTest extends TruffleWithLocalCredentialsTestContext with BinaryPackageTest
@TruffleTests class BytePackageTruffleTest extends TruffleWithLocalCredentialsTestContext with BytePackageTest
@TruffleTests class CsvPackageTruffleTest extends TruffleWithLocalCredentialsTestContext with CsvPackageTest
@TruffleTests class DatePackageTruffleTest extends TruffleWithLocalCredentialsTestContext with DatePackageTest
@TruffleTests class DecimalPackageTruffleTest extends TruffleWithLocalCredentialsTestContext with DecimalPackageTest
@TruffleTests class DoublePackageTruffleTest extends TruffleWithLocalCredentialsTestContext with DoublePackageTest
@TruffleTests class EnvironmentPackageTruffleTest extends TruffleWithLocalCredentialsTestContext with EnvironmentPackageTest
@TruffleTests class ErrorPackageTruffleTest extends TruffleWithLocalCredentialsTestContext with ErrorPackageTest
@TruffleTests class FloatPackageTruffleTest extends TruffleWithLocalCredentialsTestContext with FloatPackageTest
@TruffleTests class FunctionPackageTruffleTest extends TruffleWithLocalCredentialsTestContext with FunctionPackageTest
@TruffleTests class HttpPackageTruffleTest extends TruffleWithLocalCredentialsTestContext with HttpPackageTest
@TruffleTests class IntervalPackageTruffleTest extends TruffleWithLocalCredentialsTestContext with IntervalPackageTest
@TruffleTests class IntPackageTruffleTest extends TruffleWithLocalCredentialsTestContext with IntPackageTest
@TruffleTests class JsonPackageTruffleTest extends TruffleWithLocalCredentialsTestContext with JsonPackageTest
@TruffleTests class LongPackageTruffleTest extends TruffleWithLocalCredentialsTestContext with LongPackageTest
@TruffleTests class MathPackageTruffleTest extends TruffleWithLocalCredentialsTestContext with MathPackageTest
@TruffleTests class NullablePackageTruffleTest extends TruffleWithLocalCredentialsTestContext with NullablePackageTest
@TruffleTests class NullableTryablePackageTruffleTest extends TruffleWithLocalCredentialsTestContext with NullableTryablePackageTest
@TruffleTests class RecordPackageTruffleTest extends TruffleWithLocalCredentialsTestContext with RecordPackageTest
@TruffleTests class RegexPackageTruffleTest extends TruffleWithLocalCredentialsTestContext with RegexPackageTest
@TruffleTests class S3PackageTruffleTest extends TruffleWithLocalCredentialsTestContext with S3PackageTest
@TruffleTests class ShortPackageTruffleTest extends TruffleWithLocalCredentialsTestContext with ShortPackageTest
@TruffleTests class StringPackageTruffleTest extends TruffleWithLocalCredentialsTestContext with StringPackageTest
@TruffleTests class SuccessPackageTruffleTest extends TruffleWithLocalCredentialsTestContext with SuccessPackageTest
@TruffleTests class TimePackageTruffleTest extends TruffleWithLocalCredentialsTestContext with TimePackageTest
@TruffleTests class TimestampPackageTruffleTest extends TruffleWithLocalCredentialsTestContext with TimestampPackageTest
@TruffleTests class TryPackageTruffleTest extends TruffleWithLocalCredentialsTestContext with TryPackageTest
@TruffleTests class TypePackageTruffleTest extends TruffleWithLocalCredentialsTestContext with TypePackageTest
@TruffleTests class XmlPackageTruffleTest extends TruffleWithLocalCredentialsTestContext with XmlPackageTest
@TruffleTests class LocationPackageTruffleTest extends TruffleWithLocalCredentialsTestContext with LocationPackageTest
