pull_request_rules:
  - name: Automatic merge for Scala Steward patch updates from com.raw-labs
    conditions:
      - author=scala-steward
      - label=semver-spec-patch
      - label=com.raw-labs
      - label!=do not merge
    actions:
      merge:
        method: squash
