name: Get ANTLR4 JAR

description: Checks if a file is present in a shared location, downloads if not.

inputs:
  version:
    description: 'Version in X.y.z format'
    required: false
    default: '4.12.0'
  base_url:
    description: 'Base URL for downloading the JAR'
    required: false
    default: 'https://raw.githubusercontent.com/antlr/website-antlr4/gh-pages/download'

runs:
  using: "composite"
  steps:
    - name: Check if ANTLR JAR is present and download if not
      run: |
        if [ ! -f "$HOME/$JAR_FILE" ]; then
          echo "ANTLR JAR not found. Attempting to download..."
          if ! curl -o "$HOME/$JAR_FILE" --retry 5 --retry-delay 10 --fail "$BASE_URL/$JAR_FILE"; then
            echo "Failed to download ANTLR JAR after multiple attempts."
            exit 1
          fi
        fi
        cp "$HOME/$JAR_FILE" "$GITHUB_WORKSPACE"
      shell: bash
      env:
        SHARED_LOCATION: ${{ inputs.shared_location }}
        JAR_FILE: antlr-${{ inputs.version }}-complete.jar
        BASE_URL: ${{ inputs.base_url }}
