#!/bin/bash -e

SCRIPT_HOME="$(cd "$(dirname "$0")"; pwd)"
SNAPI_HOME="$(cd "${SCRIPT_HOME}/.."; pwd)"
cd "${SNAPI_HOME}"

# Needed to pull private deps from main repo
if [ -z "$GITHUB_TOKEN" ]; then
  echo "Error: GITHUB_TOKEN is not set. Exiting..."
  exit 1
fi
export GITHUB_TOKEN

find . -type d -name "target" -exec rm -rf {} + || true

tmp_dir=$(mktemp -d -t check-sbt-XXXXXXXXXX)
cp -R . ${tmp_dir}

docker run \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /usr/bin/docker:/usr/bin/docker \
  -v ${HOME}/.docker/config.json:/root/.docker/config.json \
  -v ${tmp_dir}:/root/ \
  -e GITHUB_TOKEN=${GITHUB_TOKEN} \
  sbtscala/scala-sbt:graalvm-community-21.0.2_1.9.9_2.12.18 \
  /bin/bash -c "set;env; cat /etc/os-release;which java;sbt clean ${1}"
