name: release custom deps
on:
  push:
    branches:
      - master
    paths:
      - 'deps/**'
  workflow_dispatch:

permissions:
  id-token: write # These permission is needed to interact with GitHub's OIDC Token endpoint
  contents: read

jobs:
  release:
    runs-on: self-hosted
    container:
      image: ghcr.io/raw-labs/raw-ci-runner:latest
      options: --user 1001
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.READ_PACKAGES }}
    steps:
      - uses: actions/checkout@v4
      - uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - uses: s4u/maven-settings-action@v3.0.0
        with:
          path: /home/sbtuser/.m2/settings.xml
          servers: '[{"id": "githubraw", "username": "gha", "password": "${{ secrets.WRITE_PACKAGES }}"}]'
      - name: publish
        working-directory: deps
        run: ./publish.sh
