on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

name: Scala Steward

jobs:
  scala-steward:
    runs-on: [ubuntu-latest]
    name: run scala steward
    steps:
      - uses: actions/checkout@v3
      - uses: scala-steward-org/scala-steward-action@v2
        with:
          github-app-id: ${{ secrets.RAW_STEWARD_APP_ID }}
          github-app-installation-id: ${{ secrets.RAW_STEWARD_APP_INSTALLATION_ID }}
          github-app-key: ${{ secrets.RAW_STEWARD_APP_PRIVATE_KEY }}
          github-app-auth-only: 'true'
          repo-config: .scala-steward.conf